### ISSUE TITLE
 Unknown arguments:      -D_WIN32_WINNT=0x0502

### ISSUE THREAD

**Issue by zinwalin** [wiranoid/breakout#1]
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/CheckIncludeFiles.cmake:63 (message):
  Unknown arguments:

    -D_WIN32_WINNT=0x0502

Call Stack (most recent call first):
  externals/openal-soft/CMakeLists.txt:944 (CHECK_INCLUDE_FILES)

-- Configuring incomplete, errors occurred!
See also "C:/src/breakout22/build/CMakeFiles/CMakeOutput.log".
See also "C:/src/breakout22/build/CMakeFiles/CMakeError.log".

**Comment by sdavydouski** [comment]
Hi,

According to [this issue](https://github.com/kcat/openal-soft/issues/183) you can fix this by updating openal-soft submodule to the latest version:

`cd externals\openal-soft`
`git checkout master`
`git pull`

Hope this helps.
Cheers.

**Comment by zinwalin** [comment]
> Hi,
> 
> According to [this issue](https://github.com/kcat/openal-soft/issues/183) you can fix this by updating openal-soft submodule to the latest version:
> 
> `cd externals\openal-soft`
> `git checkout master`
> `git pull`
> 
> Hope this helps.
> Cheers.

it works now, thanks a lot.
