### ISSUE TITLE
Unable to open files in resouces folder with Debug mode

### ISSUE THREAD

**Issue by zinwalin** [wiranoid/breakout#2]
after compile breakout target,  I copied resources folder to folder which holds exe file.  If I run exe directly, it works.  When I run it from Visual Studio 2017, it failed as follows.

![image](https://user-images.githubusercontent.com/5416196/69104748-41b2d080-0ace-11ea-9e00-11dd35f92de9.png)

![image](https://user-images.githubusercontent.com/5416196/69104656-f698bd80-0acd-11ea-961c-e68d82da55da.png)

```
3.3.0 Win32 WGL EGL VisualC
Unable to open text file ./resources/shaders/sprite/shader.frag
Unable to open text file ./resources/shaders/sprite/shader.vert
Shader program linkage failed
Vertex info
-----------
(0) : error C5145: must write to gl_Position

Unable to open text file ./resources/shaders/textrendering/shader.frag
Unable to open text file ./resources/shaders/textrendering/shader.vert
Shader program linkage failed
Vertex info
-----------
(0) : error C5145: must write to gl_Position

Unable to open text file ./resources/shaders/particle/shader.frag
Unable to open text file ./resources/shaders/particle/shader.vert
Shader program linkage failed
Vertex info
-----------
(0) : error C5145: must write to gl_Position

Unable to open text file ./resources/shaders/postprocessing/shader.frag
Unable to open text file ./resources/shaders/postprocessing/shader.vert
Shader program linkage failed
Vertex info
-----------
(0) : error C5145: must write to gl_Position

Unable to find uniform projection. It is either not declared or not used.
Unable to find uniform sprite. It is either not declared or not used.
Unable to find uniform projection. It is either not declared or not used.
Unable to open font file ./resources/fonts/PixelScreen.ttf

C:\src\breakout22\build\Debug\breakout.exe (process 147972) exited with code 3.
Press any key to close this window . . .
```

**Comment by sdavydouski** [comment]
Well, AssetsLoader::OFFSET is just stupid concept in the first place :stuck_out_tongue_winking_eye:. Usually this is handled by setting proper working directory. You can set it by right-clicking on CMakeLists.txt and choosing "Debug and Launch Settings". Then in launch.vs.json add the following line:

`"currentDir": "${workspaceRoot}"`

**Comment by zinwalin** [comment]
> Well, AssetsLoader::OFFSET is just stupid concept in the first place 😜. Usually this is handled by setting proper working directory. You can set it by right-clicking on CMakeLists.txt and choosing "Debug and Launch Settings". Then in launch.vs.json add the following line:
> 
> `"currentDir": "${workspaceRoot}"`

I add line in launch.vs.json, then clean solutions, remove contents in build folder, and use cmake to regenerate solutions.  But still not able to open resources files with Debug mode from Visual Studio.
there's no issue if run breakout.exe directly from Debug/Release folder. 

![image](https://user-images.githubusercontent.com/5416196/69149901-5d54c000-0b3c-11ea-924e-6cd1ba3c0fa2.png)

**Comment by sdavydouski** [comment]
oh, I thought you were using Visual Studio CMake project. Try then setting working directory from here:

![Screenshot_1](https://user-images.githubusercontent.com/10433437/69150427-b34c4800-0ae9-11ea-9901-672b88d380e2.png)

Working directory field should contain the path to the resources folder.

**Comment by zinwalin** [comment]
> oh, I thought you were using Visual Studio CMake project. Try then setting working directory from here:
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/10433437/69150427-b34c4800-0ae9-11ea-9901-672b88d380e2.png)
> 
> Working directory field should contain the path to the resources folder.

fantastic, all sorted.
