### ISSUE TITLE
how to disable console window when game runs? 

### ISSUE THREAD

**Issue by zinwalin** [wiranoid/breakout#3]
![image](https://user-images.githubusercontent.com/5416196/69105087-285e5400-0acf-11ea-8ff3-fd205d876990.png)

**Comment by sdavydouski** [comment]
Non-console Windows applications use the WinMain() entry point.

So this:
`int main(int argc, char* argv[]) `
should be replaced with:
`int CALLBACK WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)`

Don't forget to include <windows.h> 

You may also want to add the following line to CMakeLists.txt:
`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS")`

**Comment by zinwalin** [comment]
> Non-console Windows applications use the WinMain() entry point.
> 
> So this:
> `int main(int argc, char* argv[]) `
> should be replaced with:
> `int CALLBACK WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)`
> 
> Don't forget to include <windows.h>
> 
> You may also want to add the following line to CMakeLists.txt:
> `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS")`

awesome reply! thanks heaps.
