### ISSUE TITLE
how to render asian characters?

### ISSUE THREAD

**Issue by zinwalin** [wiranoid/breakout#6]
I loaded a chinese font, and pass characters in renderText(), only english characters were displayed. 

![image](https://user-images.githubusercontent.com/5416196/91839244-563d0f80-ec81-11ea-9034-d760518ea1f7.png)

![image](https://user-images.githubusercontent.com/5416196/91838841-b2ebfa80-ec80-11ea-9caa-1ae1e9171c6b.png)

**Comment by sdavydouski** [comment]
You need to create a texture with all font glyphs you want to display. In this project I'm using stb_truetype to do that. You can read the docs to find out how to pack non-Ascii characters. As a quick tip: you can try to play with values in `Font `struct, particularly `firstChar `and `charCount`.
This game has very basic text rendering support. For more advanced font processing/text rendering you can checkout my other [project](https://github.com/wiranoid/fuzzy).

**Comment by zinwalin** [comment]
> You need to create a texture with all font glyphs you want to display. In this project I'm using stb_truetype to do that. You can read the docs to find out how to pack non-Ascii characters. As a quick tip: you can try to play with values in `Font `struct, particularly `firstChar `and `charCount`.
> This game has very basic text rendering support. For more advanced font processing/text rendering you can checkout my other [project](https://github.com/wiranoid/fuzzy).

brilliant!
